# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
