# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20160208_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
