# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20160208_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='www.Byline'),
        ),
    ]
