# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_article_byline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-views']},
        ),
        migrations.AlterModelOptions(
            name='byline',
            options={'ordering': ['-view_count']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='byline',
        ),
        migrations.AddField(
            model_name='article',
            name='bylines',
            field=models.ManyToManyField(related_name='articles', to='www.Byline'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
