# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_auto_20160210_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'last_updated', 'ordering': ['-views']},
        ),
    ]
