# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0010_auto_20160210_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='boring',
            field=models.BooleanField(default=True),
        ),
    ]
