# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0011_article_boring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='boring',
            field=models.BooleanField(default=False),
        ),
    ]
