# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_auto_20160213_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
