# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0015_auto_20160218_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bylines',
        ),
        migrations.AddField(
            model_name='article',
            name='names',
            field=models.ManyToManyField(null=True, related_name='articles', to='www.Byline'),
        ),
    ]
