# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0017_auto_20160218_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bylines',
            field=models.ManyToManyField(related_name='articles', to='www.Byline'),
        ),
    ]
