# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0020_auto_20160219_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='byline',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
