# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0022_auto_20160220_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='byline',
            name='all_time_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='byline',
            name='weekly_rank',
            field=models.IntegerField(null=True),
        ),
    ]
